config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
# root 'players#index'

root 'pages#show', page: 'welcome'

resources :coaches, only: [:new, :create]
  
resources :players, shallow: true do 
    resources :comments
  end
  
  
  resources :sessions, only: [:new, :create, :destroy]
  
  get 'signup', to: 'coaches#new'

  get 'login', to: 'sessions#new'

  get 'comment', to: 'comments#new'

  get 'home', to: 'sessions#show'

  get 'pages/dashboard'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coach.rb
class Coach < ApplicationRecord
    has_many :players
    has_many :comments
    
    has_secure_password
    validates :email, presence: true, uniqueness: true 
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :coach
  belongs_to :player
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
  has_many :comments, -> { order('created_at DESC') }, dependent: :destroy

  has_attached_file :image, styles: { medium: "500x500>", thumb: "250x250>" }, presence: true
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/staff.rb
class Staff < ApplicationRecord
  belongs_to :coach
  belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private 

  helper_method :current_coach

  def current_coach
    @current_coach ||= Coach.find_by(id: session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to login_path, alert: 'Not authorized - you must be logged in!' if current_coach.nil?
  end
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
    def new
        @coach = Coach.new
    end

    def create
        @coach = Coach.new(coach_params)
        if @coach.save
            session[:user_id] = @coach.id
            flash[:notice] = "You have successfully signed up!"
            redirect_to root_path
        else
            render :new
        end
        
    end

    def show
        @coach = Coach.find(params[:id])
    end
    

    private

    def coach_params
        params.require(:coach).permit(:name, :email, :password, :password_confirmation)
    end
    
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authorize

    def index
        @player = Player.find(params[:player_id])
        @comments = player.comments
    end
    
    
    def new
         @player = Player.find(params[:player_id])
         @comment = Comment.new
    end
    
    def create
        @comment = Comment.new(comment_params)
        @comment.player_id = params[:player_id]
        @comment.coach_id = current_coach.id

        if @comment.save
            redirect_to player_path(params[:player_id])
        else
            render :new
        end
        
    end

    def edit
        @comment = Comment.find(params[:id])
    end



    def show
        @player = Player.find(params[:player_id])
        @coach = Coach.find(param[:coach_id])
        @comment = Comment.new
    end

    private

    def comment_params
        params.require(:comment).permit( :comment )
    end
    

    

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    before_action :authorize, except: [:show]

    def show
        page = params[:page]
 		render "pages/#{page}"
    end
    
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
    before_action :set_player, only: [:show, :edit, :update, :destroy]
    before_action :authorize


    def index
        @players = Player.all
    end


    def new
        @player = Player.new
    end
    
    def create
        @player = Player.new(player_params)
        if @player.save
            redirect_to player_path(@player)
        else
            render :new
        end
    end


    def edit
        @player = Player.find(params[:id])
    end
    
    def update
       @player = Player.find(params[:id])
        if 
            @player.update_attributes(player_params)
            redirect_to player_path
        else
            render :edit
        end
            
    end


    def destroy
        @player = Player.find(params[:id])
        @player.destroy
            redirect_to players_path
    end
    
    def show
        @player = Player.find(params[:id])
    end

    private

    def player_params
      params.require(:player).permit(:name, :grade, :number, :position1, :position2, :position3, :coordinated, :club_exp, :image, :team_id)
    end

    def set_player
        @player = Player.find(params[:id])
    end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        coach = Coach.find_by(email: params[:email])

        if coach && coach.authenticate(params[:password])
            session[:user_id] = coach.id
            redirect_to pages_dashboard_path, notice: 'Logged in!'
        else 
            flash.now.alert = 'Invalid login credentials - try again!'
            render :new
        end

    end
    
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: 'Logged out.'
    end

    def show
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coach_helper.rb
module CoachHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/coaches/new.html.erb
<body id="signup">
  <div class="container">
    <div class="row white-text">
      <div class="col s12 m4 l2"></div>
      <div class="col s12 m4 l8">
        <div class="card #43a047 green darken-1">
          <div class="card-content white-text">
            <span class="card-title">Coach Signup</span>
            <p id="alert"><%= alert %></p>
            <%= form_for @coach do |f| %>
            <div class="field">
              <%= f.label :name %>
              <%= f.text_field :name %>
            </div>
            <div class="field">
              <%= f.label :email %>
              <%= f.text_field :email %>
            </div>
            <div class="field">
              <%= f.label :password %>
              <%= f.password_field :password %>
            </div>
            <div class="field">
              <%= f.label :pasword_confirmation %>
              <%= f.password_field :password_confirmation %>
            </div>
            <div class="actions black-text"><%= f.submit %></div>
            <% end %>
          </div>
          <div class="col s12 m4 l2"></div>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/comments/new.html.erb
<div class="container">
  <div class="row">
    <div class="col s5 push-s7 black-text">
      <h1><%= @player.name %></h1>
      <p>Grade: <%= @player.grade %></p>
      <p>Primary Position: <%= @player.position1 %></p>
      <p>2nd Position: <%= @player.position2 %></p>
      <p>3rd Position: <%= @player.position3 %></p>
      <p>Coordinated: <%= @player.coordinated %></p>
      <p>Club Experience: <%= @player.club_exp %></p>
      <p>Team: <%= @player.team.level %></p>
    </div>
    <div class="col s7 pull-s5 center-align">
      <div class="row"></div>
      <div class="row"></div>
      <div class="row"></div>
      <%= image_tag @player.image.url %>
    </div>
  </div>
  <div class="row center-align">
    <div class="player-btn waves-effect waves-light btn #bdbdbd grey lighten-1">
      <%= link_to "Back to List", players_path %>
    </div>
    <div class="player-btn waves-effect waves-light btn #bdbdbd grey lighten-1">
      <%= link_to "Edit", edit_player_path(@player) %>
    </div>
    <div class="player-btn waves-effect waves-light btn #bdbdbd grey lighten-1">
      <%= link_to "Delete", player_path(@player), method: :delete, data: { confirm: "Are you sure you want to delete this player?"} %> 
    </div>
  </div>
</div>
<div class="container">
<div class="row">
  <div class="col s12">
    <div class="card #43a047 green darken-1">
      <div class="card-content white-text">
        <span class="card-title"> Coaches Comments </span>
        <%= form_for [@player, @comment] do |f| %>
        <div>
          <%= f.label :comment %>
          <%= f.text_field :comment %>
        </div>
        <div class="actions black-text"><%= f.submit "Save Comment" %></div>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Team Captain</title>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Graduate" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Oswald:200,300,400,700" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="texture #424242 grey darken-3">
    <div class="navbar-fixed">
      <nav class="row #000000 black">
        <div class="container">
          <a href="/pages/dashboard" class="brand-logo green-text darken-1 left-align" id="logo">Team Captain</a>
          <p class="col s4 push-s8" id="nav-status">
            <% if current_coach %>
            Welcome, Coach <%= current_coach.name %>
            &nbsp;&nbsp;|&nbsp;&nbsp;
            <%= link_to 'Log Out', session_path('dummy'), method: :delete %>
            <% else %>
            <%= link_to 'Log In', login_path %>
            &nbsp;&nbsp;|&nbsp;&nbsp;
            <%= link_to 'Sign Up', signup_path %>
            <% end %>
          </p>
        </div>
      </nav>
    </div>
    <%= yield %>
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.0/js/materialize.min.js"></script>
  </body>
</html>

app/views/pages/dashboard.html.erb
<body>
  <div class="container">
    <div class="row"></div>
    <div class="row"></div>
    <div class="row"></div>
    <div class="row"></div>
    <div class="row"></div>
    <div class="row"></div>
    <div class="row">
      <div class="col s12 m4">
        <div class="hoverable">
          <div class="card small">
            <div class="card-image">
              <img src="http://i.imgur.com/qVUyaB0.png">
            </div>
            <div class="card-content">
              <span class="card-title grey-text text-darken-4 center">Rosters</span>
            </div>
            <div class="card-action center">
              <a href="/players">Pre-season Prospects</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col s12 m4">
        <div class="hoverable">
          <div class="card small">
            <div class="card-image">
              <img src="http://i.imgur.com/OhcGGUv.jpg">
            </div>
            <div class="card-content">
              <span class="card-title grey-text text-darken-4 center">Team Stats Links</span>
            </div>
            <div class="card-action center">
              <a href="http://www.maxpreps.com/high-schools/south-spartans-(torrance,ca)/boys-volleyball/home.htm">MaxPreps</a>
              <a href="http://cifss.org/">CIF SS</a>
            </div>
          </div>
        </div>
      </div>
      <div class="col s12 m4">
        <div class="hoverable">
          <div class="card small">
            <div class="card-image">
              <img src="http://i.imgur.com/pSNGXuV.png">
            </div>
            <div class="card-content">
              <span class="card-title grey-text text-darken-4 center">Current Teams</span>
            </div>
            <div class="card-action center">
              <a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="Off Season">Varsity</a>
              <a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="Off Season">JV</a>
              <a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="Off Season">Frosh/Soph</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
  </div>
  <div class="row"></div>
  <div class="row"></div>
  <div class="row"></div>
  <div class="row"></div>
  <div class="row"></div>
  <div class="row"></div>
  <div class="row"></div>
  <footer class="page-footer N/A transparent" id="footer-dash">
    <div class="container">
      <div class="row">
          <h1 class="green-text darken-1 align-center" id="tag">Home of the Spartans</h1>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container right-align">
        © 2017 Copyright Text
      </div>
    </div>
  </footer>

app/views/players/edit.html.erb
<div class="container">
<div class="row">
  <div class="card #424242 grey darken-1">
    <div class="card-content white-text">
      <div class="row">
        <div class="col s2 center-align">
          <a href="/players"><i class="material-icons center">arrow_back</i></a>
        </div>
        <span class="col s10 card-title left-align">Add Player</span>
      </div>
      <p id="alert"><%= alert %></p>
      <div class="container">
        <div class="row">
          <%= form_for @player do |f| %>
          <div class="field">
            <%= f.label :name %>
            <%= f.text_field :name %>
          </div>
          <div class="field">
            <%= f.label :number %>
            <%= f.text_field :number %>
          </div>
          <div class="field black-text">
            <%= f.label :team %>
            <%= collection_select(:player, :team_id, Team.all, :id, :level) %>
          </div>
          <div class="field">
            <div class="field black-text">
              <%= f.label :grade %>
              <%= f.select :grade, ["9", "10", "11", "12"], :prompt => "Select Grade" %>
            </div>
            <div class="field black-text">
              <%= f.label :coordinated %>
              <%= f.select :coordinated, ["Yes", "No", "Has Potential", "Unknown"], :prompt => "Select Coordination"%>
            </div>
            <div class="field black-text">
              <%= f.label :position1 %>
              <%= f.select :position1, ["Unassigned", "Setter", "Opposite", "Outside", "Middle Blocker", "Libero", "Defensive Specialist", "Serving Specialist", "Team Manager", "Right Bench"], :prompt => "Primary Position" %>
            </div>
            <div class="field black-text">
              <%= f.label :position2 %>
              <%= f.select :position2, ["Unassigned", "Setter", "Opposite", "Outside", "Middle Blocker", "Libero", "Defensive Specialist", "Serving Specialist", "Team Manager", "Right Bench"], :prompt => "Secondary Position" %>
            </div>
            <div class="field black-text">
              <%= f.label :position3 %>
              <%= f.select :position3, ["Unassigned", "Setter", "Opposite", "Outside", "Middle Blocker", "Libero", "Defensive Specialist", "Serving Specialist", "Team Manager", "Right Bench"], :prompt => "Third Position" %>
            </div>
            <div class="field black-text">
              <%= f.label :club_exp %>
              <%= f.select :club_exp, ["0", "1", "2", "3", "4+"], :prompt => "Club Experience" %>
            </div>
            <%= f.file_field :image %>
            <div class="actions black-text"><%= f.submit %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/players/index.html.erb
<body class="texture">
  <div class="container">
    <p class="white-text" id="notice"><%= notice %></p>
    <div class="row"></div>
    <h6><span class="green-text darken-1">Prospect List</span></h6>
    <table class="highlight striped">
      <thead class="black-text">
        <tr>
          <th>Name</th>
          <th>Grade</th>
          <th>Position 1</th>
          <th>Position 2</th>
          <th>Position 3</th>
          <th>Coordinated</th>
          <th>Club Exp.</th>
          <th>Team</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @players.each do |player| %>
        <tr>
          <td><%= link_to player.name, player_path(player) %> </td>
          <td><%= player.grade %></td>
          <td><%= player.position1 %></td>
          <td><%= player.position2 %></td>
          <td><%= player.position3 %></td>
          <td><%= player.coordinated %></td>
          <td><%= player.club_exp %></td>
          <td><%= player.team.level %></td>
          <td>
            <a class="dropdown-button btn white blue-text" href="#" data-activates=<%= "dropdown#{player.id}" %>>Action</a>
            <ul class='dropdown-content' id= <%= "dropdown#{player.id}" %> >
              <li><%= link_to 'Edit Player', edit_player_path(player) %></li>
              <li><%= link_to 'Delete', player_path(player), method: :delete %></li>
            </ul>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <hr>
    <div class="btn white"><%= link_to "Add Player", new_player_path %></div>
  </div>
  </div>
  <footer class="page-footer N/A transparent" id="footer">
    <div class="container">
      <div class="row">
        <div class="col l4 offset-l2 s12">
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container right-align">
        © 2017 Copyright Text
      </div>
    </div>
  </footer>

app/views/players/new.html.erb
<div class="container">
<div class="row">
  <div class="card #424242 grey darken-1">
    <div class="card-content white-text">
      <div class="row">
        <div class="col s2 center-align">
          <a href="/players"><i class="material-icons center">arrow_back</i></a>
        </div>
        <span class="col s10 card-title left-align">Add Player</span>
      </div>
      <p id="alert"><%= alert %></p>
      <div class="container">
        <div class="row">
          <%= form_for @player do |f| %>
          <div class="field">
            <%= f.label :name %>
            <%= f.text_field :name %>
          </div>
          <div class="field">
            <%= f.label :number %>
            <%= f.text_field :number %>
          </div>
          <div class="field black-text">
            <%= f.label :team %>
            <%= collection_select(:player, :team_id, Team.all, :id, :level) %>
          </div>
          <div class="field">
            <div class="field black-text">
              <%= f.label :grade %>
              <%= f.select :grade, ["9", "10", "11", "12"], :prompt => "Select Grade" %>
            </div>
            <div class="field black-text">
              <%= f.label :coordinated %>
              <%= f.select :coordinated, ["Yes", "No", "Has Potential", "Unknown"], :prompt => "Select Coordination"%>
            </div>
            <div class="field black-text">
              <%= f.label :position1 %>
              <%= f.select :position1, ["Unassigned", "Setter", "Opposite", "Outside", "Middle Blocker", "Libero", "Defensive Specialist", "Serving Specialist", "Team Manager", "Right Bench"], :prompt => "Primary Position" %>
            </div>
            <div class="field black-text">
              <%= f.label :position2 %>
              <%= f.select :position2, ["Unassigned", "Setter", "Opposite", "Outside", "Middle Blocker", "Libero", "Defensive Specialist", "Serving Specialist", "Team Manager", "Right Bench"], :prompt => "Secondary Position" %>
            </div>
            <div class="field black-text">
              <%= f.label :position3 %>
              <%= f.select :position3, ["Unassigned", "Setter", "Opposite", "Outside", "Middle Blocker", "Libero", "Defensive Specialist", "Serving Specialist", "Team Manager", "Right Bench"], :prompt => "Third Position" %>
            </div>
            <div class="field black-text">
              <%= f.label :club_exp %>
              <%= f.select :club_exp, ["0", "1", "2", "3", "4+"], :prompt => "Club Experience" %>
            </div>
            <%= f.file_field :image %>
            <div class="actions black-text"><%= f.submit %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/players/show.html.erb
<div class="container">
  <div class="row">
    <div class="col s5 push-s7 black-text">
      <h1><%= @player.name %></h1>
      <p>Grade: <%= @player.grade %></p>
      <p>Primary Position: <%= @player.position1 %></p>
      <p>2nd Position: <%= @player.position2 %></p>
      <p>3rd Position: <%= @player.position3 %></p>
      <p>Coordinated: <%= @player.coordinated %></p>
      <p>Club Experience: <%= @player.club_exp %></p>
      <p>Team: <%= @player.team.level %></p>
    </div>
    <div class="col s7 pull-s5 center-align">
      <div class="row"></div>
      <div class="row"></div>
      <div class="row"></div>
      <%= image_tag @player.image.url %>
    </div>
  </div>
  <div class="row center-align">
    <div class="player-btn waves-effect waves-light btn #bdbdbd grey lighten-1">
      <%= link_to "Back to List", players_path %>
    </div>
    <div class="player-btn waves-effect waves-light btn #bdbdbd grey lighten-1">
      <%= link_to "Edit", edit_player_path %>
    </div>
    <div class="player-btn waves-effect waves-light btn #bdbdbd grey lighten-1">
      <%= link_to "Delete", player_path(@player), method: :delete, data: { confirm: "Are you sure you want to delete this player?"} %> 
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col s12">
      <div class="card #43a047 green darken-1">
        <div class="card-content white-text">
          <span class="card-title"> Coaches Comments </span>
          <div class="waves-effect waves-light btn #bdbdbd grey lighten-1">
            <%= link_to "Add Comment", new_player_comment_path(@player) %>
          </div>
          <ul>
            <% @player.comments.each do |comment| %>
            <li><%= comment.comment %></li>
            By: <%= comment.coach.name  %> &nbsp;&nbsp;
            <%= comment.created_at.strftime("%B %d %Y") %>
            <hr>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>